import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1 },
  gradient: { flex: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
  },
  headerLeft: { flex: 1 },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  title: { fontFamily: 'Orbitron-Black', fontSize: 24, color: '#fff' },
  subtitle: { fontFamily: 'Orbitron-Regular', fontSize: 14, color: '#9ca3af' },
  inboxButton: {
    position: 'relative',
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#6366f1',
  },
  badge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#ef4444',
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 1,
    minWidth: 16,
    alignItems: 'center',
  },
  badgeText: { fontFamily: 'Orbitron-Bold', fontSize: 9, color: '#fff' },
  settingsButton: { padding: 8, borderRadius: 8, backgroundColor: '#1f2937' },
  tabContainer: { flexDirection: 'row', paddingHorizontal: 20, marginBottom: 16 },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    marginHorizontal: 4,
    borderRadius: 8,
    backgroundColor: '#374151',
  },
  tabButtonActive: { backgroundColor: '#6366f1' },
  tabButtonText: { fontFamily: 'Orbitron-Regular', fontSize: 14, color: '#fff' },
  tabButtonTextActive: { color: '#fff', fontWeight: 'bold' },
  tabContent: { flex: 1, paddingHorizontal: 20 },
  widgetGrid: { width: '100%', justifyContent: 'space-between', gap: 16 },
  widgetCard: {
    backgroundColor: '#23263a',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  sectionTitleContainer: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionTitle: { fontFamily: 'Orbitron-Bold', fontSize: 18, color: '#fff', marginLeft: 8 },
  completedSectionTitle: { color: '#9CA3AF' },
  sectionDescription: { fontFamily: 'Orbitron-Regular', fontSize: 13, color: '#9ca3af', marginBottom: 8 },
  completedSectionDescription: { color: '#9CA3AF' },
  questsContainer: { gap: 12 },
  questItem: {
    backgroundColor: '#181825',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  },
  completedQuestItem: { backgroundColor: '#23263a' },
  questHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  questTitle: { fontFamily: 'Orbitron-Bold', fontSize: 15, color: '#fff' },
  completedQuestTitle: { color: '#9CA3AF' },
  questBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#23263a', borderRadius: 6, paddingHorizontal: 6, marginLeft: 8 },
  completedQuestBadge: { backgroundColor: '#181825' },
  questBadgeText: { fontFamily: 'Orbitron-Regular', fontSize: 11, color: '#8B5CF6', marginLeft: 4 },
  completedQuestBadgeText: { color: '#9CA3AF' },
  questDescription: { fontFamily: 'Orbitron-Regular', fontSize: 13, color: '#fff', marginTop: 4 },
  completedQuestDescription: { color: '#9CA3AF' },
  questReasoning: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#a3a3a3', marginTop: 2 },
  completedQuestReasoning: { color: '#a3a3a3' },
  questFooter: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 6 },
  questDifficulty: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#f59e42' },
  completedQuestDifficulty: { color: '#f59e42' },
  questXP: { fontFamily: 'Orbitron-Bold', fontSize: 12, color: '#10b981' },
  completedQuestXP: { color: '#10b981' },
  questDuration: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#60a5fa' },
  completedQuestDuration: { color: '#60a5fa' },
  questTimer: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#fbbf24', marginLeft: 'auto' },
  completeButton: { marginTop: 8, backgroundColor: '#6366f1', borderRadius: 8, paddingVertical: 8, alignItems: 'center' },
  completeButtonText: { fontFamily: 'Orbitron-Bold', color: '#fff', fontSize: 14 },
  completedBadge: { marginTop: 8, backgroundColor: '#10b981', borderRadius: 8, paddingVertical: 4, alignItems: 'center' },
  completedBadgeText: { fontFamily: 'Orbitron-Bold', color: '#fff', fontSize: 12 },
  emptyQuestState: { alignItems: 'center', padding: 16 },
  emptyQuestTitle: { fontFamily: 'Orbitron-Bold', fontSize: 16, color: '#9ca3af', marginTop: 8 },
  emptyQuestText: { fontFamily: 'Orbitron-Regular', fontSize: 13, color: '#9ca3af', marginTop: 4, textAlign: 'center' },
  achievementStats: { marginBottom: 8 },
  achievementStatsText: { fontFamily: 'Orbitron-Regular', fontSize: 13, color: '#9ca3af' },
  achievementCard: { backgroundColor: '#23263a', borderRadius: 12, padding: 12, marginBottom: 8 },
  achievementHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  achievementTitle: { fontFamily: 'Orbitron-Bold', fontSize: 15, color: '#fff' },
  achievementBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#181825', borderRadius: 6, paddingHorizontal: 6, marginLeft: 8 },
  achievementBadgeText: { fontFamily: 'Orbitron-Regular', fontSize: 11, color: '#3B82F6', marginLeft: 4 },
  achievementDescription: { fontFamily: 'Orbitron-Regular', fontSize: 13, color: '#fff', marginTop: 4 },
  achievementFooter: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 6 },
  achievementCategory: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#f59e42' },
  achievementDate: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#60a5fa' },
  goalCard: { backgroundColor: '#23263a', borderRadius: 12, padding: 12, marginBottom: 8 },
  goalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  goalTitle: { fontFamily: 'Orbitron-Bold', fontSize: 15, color: '#fff' },
  goalStatus: { backgroundColor: '#6366f1', borderRadius: 6, paddingHorizontal: 8, marginLeft: 8 },
  goalCompleted: { backgroundColor: '#10b981' },
  goalStatusText: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#fff' },
  goalDescription: { fontFamily: 'Orbitron-Regular', fontSize: 13, color: '#fff', marginTop: 4 },
  goalProgress: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 6 },
  progressBar: { flex: 1, height: 8, backgroundColor: '#181825', borderRadius: 4, overflow: 'hidden' },
  progressFill: { height: 8, backgroundColor: '#6366f1', borderRadius: 4 },
  progressText: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#fff', marginLeft: 8 },
  goalFooter: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 6 },
  goalCategory: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#f59e42' },
  goalDate: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#60a5fa' },
  valueCard: { backgroundColor: '#23263a', borderRadius: 12, padding: 12, marginBottom: 8 },
  valueTitle: { fontFamily: 'Orbitron-Bold', fontSize: 15, color: '#fff' },
  valueDescription: { fontFamily: 'Orbitron-Regular', fontSize: 13, color: '#fff', marginTop: 4 },
  valueImportance: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#f59e42', marginTop: 4 },
  journalCard: { backgroundColor: '#23263a', borderRadius: 12, padding: 12, marginBottom: 8 },
  journalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  journalDate: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#60a5fa' },
  journalTitle: { fontFamily: 'Orbitron-Bold', fontSize: 15, color: '#fff', marginTop: 4 },
  journalContent: { fontFamily: 'Orbitron-Regular', fontSize: 13, color: '#fff', marginTop: 4 },
  journalSection: { marginTop: 8 },
  journalSectionTitle: { fontFamily: 'Orbitron-Bold', fontSize: 13, color: '#f59e42' },
  journalListItem: { fontFamily: 'Orbitron-Regular', fontSize: 12, color: '#fff', marginLeft: 8, marginTop: 2 },
  emptyStateText: { fontFamily: 'Orbitron-Regular', fontSize: 14, color: '#9ca3af', textAlign: 'center', marginTop: 32 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { backgroundColor: '#23263a', borderRadius: 16, padding: 24, width: '90%', maxWidth: 400 },
  modalClose: { position: 'absolute', top: 12, right: 12, zIndex: 10 },
  modalCloseText: { fontSize: 28, color: '#fff' },
  modalTitle: { fontFamily: 'Orbitron-Bold', fontSize: 18, color: '#fff', marginBottom: 16, textAlign: 'center' },
  modalLabel: { fontFamily: 'Orbitron-Regular', fontSize: 14, color: '#9ca3af', marginTop: 12, marginBottom: 4 },
  input: { backgroundColor: '#181825', color: '#fff', borderRadius: 8, padding: 10, marginBottom: 10, fontFamily: 'Orbitron-Regular', fontSize: 14 },
  textArea: { minHeight: 60, textAlignVertical: 'top' },
  picker: { backgroundColor: '#181825', color: '#fff', borderRadius: 8, marginBottom: 10 },
  createButton: { backgroundColor: '#6366f1', borderRadius: 8, paddingVertical: 12, alignItems: 'center', marginTop: 8 },
  createButtonText: { fontFamily: 'Orbitron-Bold', color: '#fff', fontSize: 15 },
  activeTabButton: {
    backgroundColor: '#6366f1',
  },
  activeTabButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  questSection: {
    marginBottom: 24,
  },
  // Quest modal styles
  questModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  questModalContent: {
    backgroundColor: '#1f2937',
    borderRadius: 16,
    width: '90%',
    maxWidth: 600,
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: '#374151',
  },
  questModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
  },
  questModalTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  questModalTitle: {
    fontFamily: 'Orbitron-Bold',
    fontSize: 20,
    color: '#ffffff',
    marginLeft: 12,
    flex: 1,
  },
  questModalCloseButton: {
    padding: 4,
    borderRadius: 8,
    backgroundColor: '#374151',
  },
  questTypeBadge: {
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginHorizontal: 20,
    marginTop: 16,
  },
  questTypeBadgeText: {
    fontFamily: 'Orbitron-Bold',
    fontSize: 14,
    textAlign: 'center',
  },
  questModalBody: {
    flex: 1,
    padding: 20,
  },
  questDetailSection: {
    marginBottom: 24,
  },
  questDetailSectionTitle: {
    fontFamily: 'Orbitron-Bold',
    fontSize: 16,
    color: '#ffffff',
    marginBottom: 12,
  },
  questDetailDescription: {
    fontFamily: 'Orbitron-Regular',
    fontSize: 14,
    color: '#d1d5db',
    lineHeight: 20,
  },
  questDetailReasoning: {
    fontFamily: 'Orbitron-Regular',
    fontSize: 14,
    color: '#9ca3af',
    lineHeight: 20,
    fontStyle: 'italic',
  },
  questRewardsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  questRewardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#374151',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  questRewardText: {
    fontFamily: 'Orbitron-Bold',
    fontSize: 14,
    color: '#fbbf24',
  },
  questDifficultyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 2,
    gap: 6,
  },
  questDifficultyBadgeText: {
    fontFamily: 'Orbitron-Bold',
    fontSize: 12,
  },
  questDetailsGrid: {
    gap: 12,
  },
  questDetailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
  },
  questDetailLabel: {
    fontFamily: 'Orbitron-Regular',
    fontSize: 14,
    color: '#9ca3af',
  },
  questDetailValue: {
    fontFamily: 'Orbitron-Bold',
    fontSize: 14,
    color: '#ffffff',
  },
  questModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    gap: 12,
  },
  questModalButton: {
    flex: 1,
  },
  questPreviewFooter: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#374151',
  },
  questPreviewText: {
    fontFamily: 'Orbitron-Regular',
    fontSize: 11,
    color: '#6b7280',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  questCard: {
    backgroundColor: '#1f2937',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#374151',
  },
  questFrequency: {
    fontFamily: 'Orbitron-Regular',
    fontSize: 12,
    color: '#9ca3af',
  },
  systemQuestInstruction: {
    fontFamily: 'Orbitron-Regular',
    fontSize: 12,
    color: '#9ca3af',
    marginTop: 8,
  },
  goButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    backgroundColor: '#6366f1',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  goButtonText: {
    fontFamily: 'Orbitron-Bold',
    fontSize: 12,
    color: '#fff',
  },
  completedQuestCard: {
    backgroundColor: '#1f2937',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#374151',
  },
  valueHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  importanceBadge: {
    backgroundColor: '#374151',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  importanceText: {
    fontFamily: 'Orbitron-Regular',
    fontSize: 10,
    color: '#fbbf24',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  closeButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#374151',
  },
  closeButtonText: {
    fontFamily: 'Orbitron-Bold',
    fontSize: 16,
    color: '#fff',
  },
  modalBody: {
    maxHeight: 400,
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#374151',
  },
  selectedCategoryChip: {
    backgroundColor: '#f59e0b',
    borderColor: '#f59e0b',
  },
  categoryChipText: {
    fontFamily: 'Orbitron-Regular',
    fontSize: 12,
    color: '#9ca3af',
  },
  selectedCategoryChipText: {
    color: '#ffffff',
  },
});

export default styles; 