import { Goal, Task, UserStats, JournalEntry, CoreValue, PersonalAchievement, SystemQuest, QuestTrigger } from '@/types/app';
import { generateIntelligentTasks, generateIntelligentTasksForGoal } from './intelligentTaskGeneration';
import aiService from './aiService';

// All storage is now handled by the database. Do not use this file.
export const getGoals = () => { throw new Error('Use database storage'); };
export const getTasks = () => { throw new Error('Use database storage'); };
export const getSystemQuests = () => { throw new Error('Use database storage'); };
export const getUserStats = () => { throw new Error('Use database storage'); };
export const getJournalEntries = () => { throw new Error('Use database storage'); };
export const getCoreValues = () => { throw new Error('Use database storage'); };
export const getPersonalAchievements = () => { throw new Error('Use database storage'); };
export const getQuestTriggers = () => { throw new Error('Use database storage'); };
export const getHabits = () => { throw new Error('Use database storage'); };
export const addGoal = () => { throw new Error('Use database storage'); };
export const updateGoal = () => { throw new Error('Use database storage'); };
export const addTask = () => { throw new Error('Use database storage'); };
export const addSystemQuest = () => { throw new Error('Use database storage'); };
export const addJournalEntry = () => { throw new Error('Use database storage'); };
export const addCoreValue = () => { throw new Error('Use database storage'); };
export const addPersonalAchievement = () => { throw new Error('Use database storage'); };
export const generateAIQuestsFromJournalEntry = () => { throw new Error('Use database storage'); };
export const generateAIQuestsFromContext = () => { throw new Error('Use database storage'); };
export const clearAllData = () => { throw new Error('Use database storage'); };
export const initializeSystemQuests = () => { throw new Error('Use database storage'); };
export const generateIntelligentTasksFromContext = () => { throw new Error('Use database storage'); };
export const completeTask = () => { throw new Error('Use database storage'); };
export const addGoalWithIntelligentTasks = () => { throw new Error('Use database storage'); };
export const getSuggestedGoals = () => { throw new Error('Use database storage'); };
export const addHabit = () => { throw new Error('Use database storage'); };
export const updateHabit = () => { throw new Error('Use database storage'); };
export const deleteHabit = () => { throw new Error('Use database storage'); };
export const toggleHabitCompletion = () => { throw new Error('Use database storage'); };
export const cleanupTemplateHabits = () => { throw new Error('Use database storage'); };